GET http://localhost:3000/users

### Usúario Comum
POST http://localhost:3000/users
Content-Type: application/json

{
    "name": "Larissa",
    "email": "larissa@test.com",
    "password": "123456"
}

### Usúario Partner
POST http://localhost:3000/partners/users
Content-Type: application/json

{
    "name": "Carlos",
    "email": "carlos@test.com",
    "password": "123456"
}

### Login
POST http://localhost:3000/auth/login
Content-Type: application/json

{
    "email": "carlos@test.com",
    "password": "123456"
}

### Partner
POST http://localhost:3000/partners
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NiwibmFtZSI6IkNhcmxvcyIsImVtYWlsIjoiY2FybG9zQHRlc3QuY29tIiwicm9sZXMiOlsiUEFSVE5FUiJdLCJjcmVhdGVkQXQiOiIyMDI0LTA2LTE5VDE1OjQxOjM0LjUzMloiLCJ1cGRhdGVkQXQiOiIyMDI0LTA2LTE5VDE1OjQxOjM0LjUzMloiLCJpYXQiOjE3MTg5NzkyNDIsImV4cCI6MTcxODk4OTI0Mn0.Ea97mrGgtZgvXefJeLpUkkfXgzaUWtuzYeVYnyGgeV4

{
    "name": "partner 1"
}

### Partner
GET http://localhost:3000/partners
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NiwibmFtZSI6IkNhcmxvcyIsImVtYWlsIjoiY2FybG9zQHRlc3QuY29tIiwicm9sZXMiOlsiUEFSVE5FUiJdLCJjcmVhdGVkQXQiOiIyMDI0LTA2LTE5VDE1OjQxOjM0LjUzMloiLCJ1cGRhdGVkQXQiOiIyMDI0LTA2LTE5VDE1OjQxOjM0LjUzMloiLCJpYXQiOjE3MTg5NzkyNDIsImV4cCI6MTcxODk4OTI0Mn0.Ea97mrGgtZgvXefJeLpUkkfXgzaUWtuzYeVYnyGgeV4

{
    "name": "partner 1"
}

### Criar um Evento
POST http://localhost:3000/events
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NiwibmFtZSI6IkNhcmxvcyIsImVtYWlsIjoiY2FybG9zQHRlc3QuY29tIiwicm9sZXMiOlsiUEFSVE5FUiJdLCJjcmVhdGVkQXQiOiIyMDI0LTA2LTE5VDE1OjQxOjM0LjUzMloiLCJ1cGRhdGVkQXQiOiIyMDI0LTA2LTE5VDE1OjQxOjM0LjUzMloiLCJpYXQiOjE3MTg5NzkyNDIsImV4cCI6MTcxODk4OTI0Mn0.Ea97mrGgtZgvXefJeLpUkkfXgzaUWtuzYeVYnyGgeV4
Content-Type: application/json

{
    "name": "Evento 01",
    "description": "Descrição do evento 01",
    "date": "2024-06-21T23:21:34.60"
}

### Listar os Eventos
GET http://localhost:3000/events
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NiwibmFtZSI6IkNhcmxvcyIsImVtYWlsIjoiY2FybG9zQHRlc3QuY29tIiwicm9sZXMiOlsiUEFSVE5FUiJdLCJjcmVhdGVkQXQiOiIyMDI0LTA2LTE5VDE1OjQxOjM0LjUzMloiLCJ1cGRhdGVkQXQiOiIyMDI0LTA2LTE5VDE1OjQxOjM0LjUzMloiLCJpYXQiOjE3MTg5NzkyNDIsImV4cCI6MTcxODk4OTI0Mn0.Ea97mrGgtZgvXefJeLpUkkfXgzaUWtuzYeVYnyGgeV4
