GET http://localhost:3000/users

### Usúario Comum
POST http://localhost:3000/users
Content-Type: application/json

{
    "name": "Larissa",
    "email": "larissa@test.com",
    "password": "123456"
}

### Usúario Partner
POST http://localhost:3000/partners/users
Content-Type: application/json

{
    "name": "Carlos",
    "email": "carlos@test.com",
    "password": "123456"
}

### Login
POST http://localhost:3000/auth/login
Content-Type: application/json

{
    "email": "carlos@test.com",
    "password": "123456"
}

### Partner
POST http://localhost:3000/partners
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NiwibmFtZSI6IkNhcmxvcyIsImVtYWlsIjoiY2FybG9zQHRlc3QuY29tIiwicm9sZXMiOlsiUEFSVE5FUiJdLCJjcmVhdGVkQXQiOiIyMDI0LTA2LTE5VDE1OjQxOjM0LjUzMloiLCJ1cGRhdGVkQXQiOiIyMDI0LTA2LTE5VDE1OjQxOjM0LjUzMloiLCJpYXQiOjE3MTg4OTk0NTgsImV4cCI6MTcxODkwOTQ1OH0.ftWgrQrgnDYTsYbc2u8lHfaFbVBYbVFPZZMraQ3VwqA

{
    "name": "partner 1"
}